

-- 친구정보
-- 친구정보, 친구이름, 친구전화번호, 친구이메일, 친구주소, 친구사진 // 오토 인클루먼트
CREATE TABLE PHONEINFO_BASIC(
IDX INT NOT NULL,
FR_NAME VARCHAR(20) NOT NULL,
FR_PHONENUMBER VARCHAR(20) NOT NULL,
FR_EMAIL VARCHAR(20),
FR_ADDRESS VARCHAR(20),
FR_REGDATE DATETIME DEFAULT current_timestamp,
CONSTRAINT PHONEINFO_BASIC_IDX_PK PRIMARY KEY(IDX)
);

CREATE TABLE PHONEINFO_UNIV(
IDX INT(6) NOT NULL,
FR_U_MAJOR VARCHAR(20) DEFAULT 'N' NOT NULL,
FR_U_YEAR INT DEFAULT 1 NOT NULL,
FR_REF INT NOT NULL,
CONSTRAINT PHONEINFO_UNIV_IDX_PK primary key(IDX),
CONSTRAINT PHONEINFO_UNIV_FR_REF_FK FOREIGN KEY(FR_REF) REFERENCES PHONEINFO_BASIC(IDX)
);


CREATE TABLE PHONEINFO_COM(
IDX INT NOT NULL,
FR_C_COMPANY VARCHAR(20) DEFAULT 'N' NOT NULL,
FR_REF INT NOT NULL,
CONSTRAINT PHONEINFO_COM_IDX_PK PRIMARY KEY(IDX),
CONSTRAINT PHONEINFO_COM_FR_REF_FK FOREIGN KEY(FR_REF) REFERENCES PHONEINFO_BASIC(IDX)
);

