
-- 1. 대학친구의 모든 데이터를 검색하기 위한 질의 (join필요)
-- 이름으로 검색, 전화번호로 검색

SELECT * FROM PHONEINFO_UNIV
INNER JOIN PHONEINFO_BASIC ON PHONEINFO_UNIV.FR_REF=PHONEINFO_BASIC.IDX
WHERE FR_NAME = '홍길동';

-- 2. 회사친구의 모든 데이터를 검색하기 위한 질의 (join필요)
-- 이름으로 검색, 전화번호로 검색

SELECT * FROM PHONEINFO_COM
INNER JOIN PHONEINFO_BASIC ON PHONEINFO_COM.FR_REF=PHONEINFO_BASIC.IDX
WHERE FR_PHONENUMBER='112';

-- 3. 회사친구, 대학친구 데이터를 보기위한 각 VIEW를 생성 합시다.

CREATE OR REPLACE VIEW PHONEINFO_UNIV_VIEW
AS
SELECT PHONEINFO_BASIC.IDX 'BASIC_IDX', PHONEINFO_BASIC.FR_NAME, PHONEINFO_BASIC.FR_PHONENUMBER, PHONEINFO_BASIC.FR_EMAIL,
PHONEINFO_BASIC.FR_ADDRESS, PHONEINFO_BASIC.FR_REGDATE, PHONEINFO_UNIV.IDX 'UNIV_IDX', PHONEINFO_UNIV.FR_U_MAJOR, PHONEINFO_UNIV.FR_U_YEAR
FROM PHONEINFO_UNIV
INNER JOIN PHONEINFO_BASIC ON PHONEINFO_UNIV.FR_REF=PHONEINFO_BASIC.IDX;

DROP VIEW PHONEINFO_COM_VIEW;

SELECT * FROM PHONEINFO_COM_VIEW;

CREATE OR REPLACE VIEW PHONEINFO_COM_VIEW
AS
SELECT PHONEINFO_BASIC.IDX 'BASIC_IDX', PHONEINFO_BASIC.FR_NAME, PHONEINFO_BASIC.FR_PHONENUMBER, PHONEINFO_BASIC.FR_EMAIL,
PHONEINFO_BASIC.FR_ADDRESS, PHONEINFO_BASIC.FR_REGDATE, PHONEINFO_COM.IDX 'COM.IDX', PHONEINFO_COM.FR_C_COMPANY
FROM PHONEINFO_COM
INNER JOIN PHONEINFO_BASIC ON PHONEINFO_COM.FR_REF=PHONEINFO_BASIC.IDX;


-- 5. 회사친구, 대학친구의 데이터를 입력하기 위한 INSERT 문을 작성합시다.

INSERT INTO PHONEINFO_BASIC VALUES(PHONEINFO_BASIC_SEQ.NEXTVAL,'SCOTT','112','NAVER','LA',SYSDATE);
INSERT INTO PHONEINFO_COM VALUES(PHONEINFO_COM_SEQ.NEXTVAL,'비트',PHONEINFO_BASIC_SEQ.CURRVAL);


INSERT INTO PHONEINFO_BASIC VALUES(PHONEINFO_BASIC_SEQ.NEXTVAL,'SCOTT','112','NAVER','LA',SYSDATE);
INSERT INTO PHONEINFO_UNIV VALUES(PHONEINFO_UNIV_SEQ.NEXTVAL,'비트과',3,PHONEINFO_BASIC_SEQ.CURRVAL);


-- 6. 회사친구, 대학친구 삭제를 위한 SQL을 작성합시다.
-- DDL로 테이블 만들 때 참조되는 키값에 대한 ON DELETE CASCADE를 했습니다.

DELETE FROM PHONEINFO_BASIC WHERE FR_PHONENUMBER='112';

DELETE FROM PHONEINFO_BASIC WHERE FR_NAME='홍길동';


-- 7. 빠른검색을 위한 인덱스 설정을 합시다.(이름, 전화번호)
CREATE INDEX IDX_PHONEINFO_BASIC_FR_NAME ON PHONEINFO_BASIC(FR_NAME);

CREATE INDEX IDX_PHONEINFO_BASIC_FR_PHONENUMBER 
ON PHONEINFO_BASIC(FR_PHONENUMBER);












